### ISSUE TITLE
App doesn't start if phone is rooted

### ISSUE THREAD

**Issue by loviuz** [rewanth1997/Damn-Vulnerable-Bank#2]
Is it normal that the app doesn't run if my phone is rooted? A "Phone is rooted" message appears and the app doesn't start. I'm not familiar with java so I don't know how to remove this block. I want to test only network and data exchange issues.
Thanks!

**Comment by jaiswalakshansh** [comment]
Hi loviuz yes its completely normal that in rooted device the app should not start to bypass it in your condition what you can do is once you have cloned the repo open the DamnVulnerable folder in android studio then in Mainactivity java class in Oncreate method you can remove root check method and then rebuild an apk for yourself and it should be good thereafter.

**Comment by loviuz** [comment]
thanks!
